swagger-editor:
  image: swaggerapi/swagger-editor
  container_name: "swagger-editor"
  ports:
    - "8081:8080"

swagger-ui:
  image: swaggerapi/swagger-ui
  container_name: "swagger-ui"
  ports:
    - "8082:8080"
  volumes:
    - ./swagger/swagger.json:/swagger.json
  environment:
    SWAGGER_JSON: /swagger.json
    # API_URL: ""

swagger-api:
  image: matsudachikara/swagger-mock-api
  container_name: "swagger-api"
  ports:
    - "8083:8000"
  volumes:
    - ./swagger:/data
